version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15-alpine
    container_name: tachyon-postgres
    environment:
      POSTGRES_DB: tachyon_messenger
      POSTGRES_USER: tachyon_user
      POSTGRES_PASSWORD: tachyon_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - tachyon-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tachyon_user -d tachyon_messenger"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: tachyon-redis
    command: redis-server --appendonly yes --requirepass redis_password
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - tachyon-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # User Service
  user-service:
    build:
      context: .
      dockerfile: services/user/Dockerfile
    container_name: tachyon-user-service
    ports:
      - "8081:8081"
    environment:
      # Database configuration
      - DATABASE_URL=postgres://tachyon_user:tachyon_password@postgres:5432/tachyon_messenger?sslmode=disable
      
      # Redis configuration
      - REDIS_URL=redis://:redis_password@redis:6379
      
      # JWT configuration
      - JWT_SECRET=tachyon-super-secret-jwt-key-change-in-production-12345
      
      # Server configuration
      - USER_SERVICE_PORT=8081
      - SERVER_PORT=8081
      
      # Environment settings
      - ENVIRONMENT=development
      - GIN_MODE=debug
      
      # Logging
      - LOG_LEVEL=info
      - LOG_FORMAT=json
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - tachyon-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      start_period: 40s
      retries: 3
    volumes:
      # Mount logs directory for development
      - ./logs:/app/logs
    labels:
      - "com.tachyon.service=user-service"
      - "com.tachyon.version=1.0.0"
      - "com.tachyon.description=Tachyon User Management Service"

  # Chat Service
  chat-service:
    build:
      context: .
      dockerfile: services/chat/Dockerfile
    container_name: tachyon-chat-service
    ports:
      - "8082:8082"
    environment:
      # Database configuration
      - DATABASE_URL=postgres://tachyon_user:tachyon_password@postgres:5432/tachyon_messenger?sslmode=disable
      
      # Redis configuration
      - REDIS_URL=redis://:redis_password@redis:6379
      
      # JWT configuration (ДОЛЖЕН БЫТЬ ОДИНАКОВЫМ с User Service!)
      - JWT_SECRET=tachyon-super-secret-jwt-key-change-in-production-12345
      
      # Server configuration
      - CHAT_SERVICE_PORT=8082
      - SERVER_PORT=8082
      
      # Environment settings
      - ENVIRONMENT=development
      - GIN_MODE=debug
      
      # Logging
      - LOG_LEVEL=info
      - LOG_FORMAT=json
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      user-service:
        condition: service_healthy
    networks:
      - tachyon-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      start_period: 40s
      retries: 3
    volumes:
      # Mount logs directory for development
      - ./logs:/app/logs
    labels:
      - "com.tachyon.service=chat-service"
      - "com.tachyon.version=1.0.0"
      - "com.tachyon.description=Tachyon Chat Service with WebSocket"

  # Gateway Service (Reverse Proxy)
  gateway:
    build:
      context: .
      dockerfile: services/gateway/Dockerfile
    container_name: tachyon-gateway
    ports:
      - "8080:8080"
    environment:
      # Service URLs
      - USER_SERVICE_URL=http://user-service:8081
      - CHAT_SERVICE_URL=http://chat-service:8082
      
      # Server configuration
      - SERVER_PORT=8080
      
      # Environment settings
      - ENVIRONMENT=development
      - GIN_MODE=debug
      
      # Logging
      - LOG_LEVEL=info
      - LOG_FORMAT=json
    depends_on:
      user-service:
        condition: service_healthy
      chat-service:
        condition: service_healthy
    networks:
      - tachyon-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3
    labels:
      - "com.tachyon.service=gateway"
      - "com.tachyon.version=1.0.0"
      - "com.tachyon.description=Tachyon API Gateway"

volumes:
  postgres_data:
    driver: local
    name: tachyon_postgres_data
  redis_data:
    driver: local
    name: tachyon_redis_data

networks:
  tachyon-network:
    driver: bridge
    name: tachyon-network
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16