version: '3.8'

services:
  # ==============================================
  # Infrastructure Services
  # ==============================================
  
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: tachyon-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-tachyon_messenger}
      POSTGRES_USER: ${POSTGRES_USER:-tachyon_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tachyon_password}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - tachyon-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-tachyon_user} -d ${POSTGRES_DB:-tachyon_messenger}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    labels:
      - "com.tachyon.service=postgres"
      - "com.tachyon.version=15"
      - "com.tachyon.description=PostgreSQL Database"

  # Redis Cache & Session Store
  redis:
    image: redis:7-alpine
    container_name: tachyon-redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis_password}
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - tachyon-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    labels:
      - "com.tachyon.service=redis"
      - "com.tachyon.version=7"
      - "com.tachyon.description=Redis Cache and Session Store"

  # ==============================================
  # Core Application Services
  # ==============================================

  # User Management Service
  user-service:
    build:
      context: .
      dockerfile: services/user/Dockerfile
    container_name: tachyon-user-service
    ports:
      - "${USER_SERVICE_PORT:-8081}:8081"
    env_file:
      - .env
    environment:
      - SERVER_PORT=8081
      - USER_SERVICE_PORT=8081
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - GIN_MODE=${GIN_MODE:-debug}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - tachyon-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      start_period: 40s
      retries: 3
    volumes:
      - ./logs:/app/logs
    labels:
      - "com.tachyon.service=user-service"
      - "com.tachyon.version=1.0.0"
      - "com.tachyon.description=Tachyon User Management Service"

  # Chat & Messaging Service
  chat-service:
    build:
      context: .
      dockerfile: services/chat/Dockerfile
    container_name: tachyon-chat-service
    ports:
      - "${CHAT_SERVICE_PORT:-8082}:8082"
    env_file:
      - .env
    environment:
      - SERVER_PORT=8082
      - CHAT_SERVICE_PORT=8082
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - GIN_MODE=${GIN_MODE:-debug}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      user-service:
        condition: service_healthy
    networks:
      - tachyon-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      start_period: 40s
      retries: 3
    volumes:
      - ./logs:/app/logs
    labels:
      - "com.tachyon.service=chat-service"
      - "com.tachyon.version=1.0.0"
      - "com.tachyon.description=Tachyon Chat Service with WebSocket Support"

  # Task Management Service
  task-service:
    build:
      context: .
      dockerfile: services/task/Dockerfile
    container_name: tachyon-task-service
    ports:
      - "${TASK_SERVICE_PORT:-8083}:8083"
    env_file:
      - .env
    environment:
      - SERVER_PORT=8083
      - TASK_SERVICE_PORT=8083
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - GIN_MODE=${GIN_MODE:-debug}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      user-service:
        condition: service_healthy
    networks:
      - tachyon-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8083/health"]
      interval: 30s
      timeout: 10s
      start_period: 40s
      retries: 3
    volumes:
      - ./logs:/app/logs
    labels:
      - "com.tachyon.service=task-service"
      - "com.tachyon.version=1.0.0"
      - "com.tachyon.description=Tachyon Task Management Service"
  
  # Calendar & Events Service
  calendar-service:
    build:
      context: .
      dockerfile: services/calendar/Dockerfile
    container_name: tachyon-calendar-service
    ports:
      - "${CALENDAR_SERVICE_PORT:-8084}:8084"
    env_file:
      - .env
    environment:
      - SERVER_PORT=8084
      - CALENDAR_SERVICE_PORT=8084
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - GIN_MODE=${GIN_MODE:-debug}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      user-service:
        condition: service_healthy
    networks:
      - tachyon-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8084/health"]
      interval: 30s
      timeout: 10s
      start_period: 40s
      retries: 3
    volumes:
      - ./logs:/app/logs
    labels:
      - "com.tachyon.service=calendar-service"
      - "com.tachyon.version=1.0.0"
      - "com.tachyon.description=Tachyon Calendar and Events Service"
  
  # Polls & Surveys Service
  poll-service:
    build:
      context: .
      dockerfile: services/poll/Dockerfile
    container_name: tachyon-poll-service
    ports:
      - "${POLL_SERVICE_PORT:-8085}:8085"
    env_file:
      - .env
    environment:
      - SERVER_PORT=8085
      - POLL_SERVICE_PORT=8085
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - GIN_MODE=${GIN_MODE:-debug}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      user-service:
        condition: service_healthy
    networks:
      - tachyon-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8085/health"]
      interval: 30s
      timeout: 10s
      start_period: 40s
      retries: 3
    volumes:
      - ./logs:/app/logs
    labels:
      - "com.tachyon.service=poll-service"
      - "com.tachyon.version=1.0.0"
      - "com.tachyon.description=Tachyon Polls and Surveys Service"

  # Notification Service
  notification-service:
    build:
      context: .
      dockerfile: services/notification/Dockerfile
    container_name: tachyon-notification-service
    ports:
      - "${NOTIFICATION_SERVICE_PORT:-8087}:8087"
    env_file:
      - .env
    environment:
      - SERVER_PORT=8087
      - NOTIFICATION_SERVICE_PORT=8087
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - GIN_MODE=${GIN_MODE:-debug}
      # Email configuration
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME:-Tachyon Messenger}
      # Notification worker configuration
      - NOTIFICATION_CONCURRENT_WORKERS=${NOTIFICATION_CONCURRENT_WORKERS:-5}
      - NOTIFICATION_QUEUE_SIZE=${NOTIFICATION_QUEUE_SIZE:-1000}
      - NOTIFICATION_RETRY_ATTEMPTS=${NOTIFICATION_RETRY_ATTEMPTS:-3}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      user-service:
        condition: service_healthy
    networks:
      - tachyon-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8087/health"]
      interval: 30s
      timeout: 10s
      start_period: 40s
      retries: 3
    volumes:
      - ./logs:/app/logs
    labels:
      - "com.tachyon.service=notification-service"
      - "com.tachyon.version=1.0.0"
      - "com.tachyon.description=Tachyon Notification Service with Email Support"

  # ==============================================
  # API Gateway (Reverse Proxy)
  # ==============================================

  gateway:
    build:
      context: .
      dockerfile: services/gateway/Dockerfile
    container_name: tachyon-gateway
    ports:
      - "${GATEWAY_PORT:-8080}:8080"
    env_file:
      - .env
    environment:
      # Service URLs - используем внутренние Docker имена сервисов
      - USER_SERVICE_URL=http://user-service:8081
      - CHAT_SERVICE_URL=http://chat-service:8082
      - TASK_SERVICE_URL=http://task-service:8083
      - CALENDAR_SERVICE_URL=http://calendar-service:8084
      - POLL_SERVICE_URL=http://poll-service:8085
      - NOTIFICATION_SERVICE_URL=http://notification-service:8087
      
      # Gateway configuration
      - SERVER_PORT=8080
      - GATEWAY_PORT=8080
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - GIN_MODE=${GIN_MODE:-debug}
      
      # CORS settings
      - ENABLE_CORS=${ENABLE_CORS:-true}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000,http://localhost:8080}
    depends_on:
      user-service:
        condition: service_healthy
      chat-service:
        condition: service_healthy
      task-service:
        condition: service_healthy
      calendar-service:
        condition: service_healthy
      poll-service:
        condition: service_healthy
      notification-service:
        condition: service_healthy
    networks:
      - tachyon-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      start_period: 45s
      retries: 3
    volumes:
      - ./logs:/app/logs
    labels:
      - "com.tachyon.service=gateway"
      - "com.tachyon.version=1.0.0"
      - "com.tachyon.description=Tachyon API Gateway and Reverse Proxy"

# ==============================================
# Volumes
# ==============================================

volumes:
  postgres_data:
    driver: local
    name: tachyon_postgres_data
    labels:
      - "com.tachyon.volume=database"
      
  redis_data:
    driver: local
    name: tachyon_redis_data
    labels:
      - "com.tachyon.volume=cache"

# ==============================================
# Networks
# ==============================================

networks:
  tachyon-network:
    driver: bridge
    name: tachyon-network
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
    labels:
      - "com.tachyon.network=main"
      - "com.tachyon.description=Main network for Tachyon Messenger services"